version: '3.5'

services:
  php:
    build:
        context: .
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
      - app-network
    depends_on:
        - "db"
    ports:
        - 80:80
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local